---
title: "Prüfung"
subtitle: "CAS Datenanalyse Modul B1"
author: "Stefan Schmidt"
date: "27.05.2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data.path <- "/Users/schmis12/wrk/studio/ZHAW_CAS_Data_Analysis/Pruefung_B1/data/"
load(paste0(data.path, "Pruefung.rda"))
```


# Aufgabe 1

```{r}

# table
# read.table(paste0(data.path, "softdrink.dat"), header = TRUE)

# xls
# library(readxl)
# df <- read_xls(paste0(data.path, "Alpenquerender_Gueterverkehr_Schiene.xls"))

# dat
#library(readr)
#df <- read.csv(paste0(data.path, "Windmuehle.dat"), header = TRUE)

# csv
salary <- read.csv(paste0(data.path, "salary.csv"), header=TRUE)

```


## Scatterplot

```{r}

# plot
par(mfrow = c(1, 1))
plot(
  y ~ experience,
  data = salary,
  col = education,
  pch = education,
  xlim = c(0, 40),
  ylim = c(10000, 150000),
  xlab = "Berufserfahrung",
  ylab = "Jahreslohn"
)
legend(
  "topleft",
  c("Berufslehre", "Maturität", "Hochschulabschluss"),
  col = 1:3,
  pch = 1:3
)
```


## Modell und Residualanalyse

```{r}
fit.sal <- lm(y ~ experience + education, data = salary)
par(mfrow = c(1, 3))
plot(fit.sal, 1:3)

# mit Simulationen
load(paste0(data.path, 'resplot.rda'))
par(mfrow = c(1, 3))
resplot(fit.sal, 1:3)

```




# Aufgabe 2

